<?echo "<?xml version=\"1.0\" ?>";?>
<root>
	<data>
		<row>
			<cell>Nombre</cell>
			<cell>Fruit</cell>
			<cell>Vegetable</cell>
		</row>
		<row>
			<cell>Capitan</cell>
			<cell>Banana</cell>
			<cell>Zucchini</cell>
		</row>
		<row>
			<cell>Admiral</cell>
			<cell>Melon</cell>
			<cell>Carrot</cell>
		</row>
		<row>
			<cell>Midshipman</cell>
			<cell>Naranja</cell>
			<cell>Potatoe</cell>
		</row>
	</data>
</root>
